-- Create showcase_items table
CREATE TABLE public.showcase_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_slug TEXT NOT NULL DEFAULT 'default',
  location_label TEXT NOT NULL,
  price_label TEXT NOT NULL,
  detail_url TEXT NOT NULL,
  poster_bucket TEXT NOT NULL DEFAULT 'showcase-posters',
  poster_path TEXT NOT NULL,
  video_bucket TEXT NOT NULL DEFAULT 'showcase-videos',
  video_mp4_path TEXT,
  video_webm_path TEXT,
  published BOOLEAN NOT NULL DEFAULT false,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.showcase_items ENABLE ROW LEVEL SECURITY;

-- Public can read published items
CREATE POLICY "Public can read published showcase items" 
ON public.showcase_items 
FOR SELECT 
USING (published = true);

-- Team members can do everything
CREATE POLICY "Team members can manage showcase items" 
ON public.showcase_items 
FOR ALL 
USING (is_team_member());

-- Add updated_at trigger
CREATE TRIGGER update_showcase_items_updated_at
BEFORE UPDATE ON public.showcase_items
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Create storage buckets
INSERT INTO storage.buckets (id, name, public) VALUES ('showcase-posters', 'showcase-posters', true);
INSERT INTO storage.buckets (id, name, public) VALUES ('showcase-videos', 'showcase-videos', false);

-- Storage policies for showcase-posters (public bucket)
CREATE POLICY "Public can view poster images" 
ON storage.objects 
FOR SELECT 
USING (bucket_id = 'showcase-posters');

CREATE POLICY "Team can upload poster images" 
ON storage.objects 
FOR INSERT 
WITH CHECK (bucket_id = 'showcase-posters' AND is_team_member());

CREATE POLICY "Team can update poster images" 
ON storage.objects 
FOR UPDATE 
USING (bucket_id = 'showcase-posters' AND is_team_member());

CREATE POLICY "Team can delete poster images" 
ON storage.objects 
FOR DELETE 
USING (bucket_id = 'showcase-posters' AND is_team_member());

-- Storage policies for showcase-videos (private bucket)
CREATE POLICY "Team can view video files" 
ON storage.objects 
FOR SELECT 
USING (bucket_id = 'showcase-videos' AND is_team_member());

CREATE POLICY "Team can upload video files" 
ON storage.objects 
FOR INSERT 
WITH CHECK (bucket_id = 'showcase-videos' AND is_team_member());

CREATE POLICY "Team can update video files" 
ON storage.objects 
FOR UPDATE 
USING (bucket_id = 'showcase-videos' AND is_team_member());

CREATE POLICY "Team can delete video files" 
ON storage.objects 
FOR DELETE 
USING (bucket_id = 'showcase-videos' AND is_team_member());